### ISSUE TITLE
dependancy issue

### ISSUE THREAD

**Issue by njliang** [ndevilla/iniparser#94] opened 2018-06-08 07:21 UTC
**_make example_** can not gen a new execute file when the files of **_src_** directory  are modified.

**Comment by lmoellendorf** [comment] 2024-02-03 19:06
I cannot reproduce this, so I will close this issue.

@njliang
Feel free to provide steps and an example to reproduce if you think this is still an issue.

**Closed by lmoellendorf** 2024-02-03 19:06 UTC
