### ISSUE TITLE
support dots in key and UTF8 text

### ISSUE THREAD

**Issue by renegade091** [ndevilla/iniparser#67] opened 2015-12-21 10:45 UTC
I have a problem that the keys are not allowed to have dots e.g. "10.123=example".
Moreover UTF8 files cannot be read e.g. a string value "10.123="Grüzi"

**Comment by daniwebCH** [comment] 2018-03-09 08:45
Is there any update regarding the support of accents?    e.g.  é,à,...

**Comment by dofuuz** [comment] 2022-07-19 04:24
Possible fix: #103

**Comment by lmoellendorf** [comment] 2024-03-02 23:39
@renegade091 @daniwebCH @dofuuz 
Sorry, but I cannot reproduce these issues. I added commit ab196cb3cfc7efdd0bc5a3a7475a373a88b16407 to Test UTF-8 and dots in keys and the [test passe](https://gitlab.com/iniparser/iniparser-meta/-/jobs/6304127136).

For now I will close this issue.

If this is a Windows issue, please help us to get the test build and run on our [Windows runner](https://gitlab.com/iniparser/iniparser-meta/-/blob/main/.gitlab-ci.yml?ref_type=heads#L86) so we can reproduce it. Then this issue may be re-opened.

**Closed by lmoellendorf** 2024-03-02 23:39 UTC

**Comment by dofuuz** [comment] 2024-03-15 07:19
@lmoellendorf Strange. I cannot reproduce those problem. 😕
Could you merge those 5a5ff19 test cases to master anyway?
