### ISSUE TITLE
Please avoid using sscanf as it is not portable

### ISSUE THREAD

**Issue by sconstanter** [ndevilla/iniparser#43] opened 2014-10-02 12:21 UTC
Hi,

The iniparser library is making use of the sscanf function. This function is not portable in the sense that it is locale dependant. This function behaves for example different on an english computer compared with running it on a korean computer. 

Is there any chance to get rid of it?

Thanks in advance!

Best regards,
sconstanter

**Comment by SimonHeffer** [comment] 2018-07-20 08:39
Hi,
We've got a similar issue with a Japanese locale on AIX and, lately, Windows builds (which don't seem locale related). Our particular issue is with reading the section name. I'm thinking that can be replaced with a simple strncpy e.g.
`strncpy(section,line+1,len-2);`

**Comment by hramrach** [comment] 2024-02-11 23:34
The length is not known, however. It's determined by the `sscanf`

iniparser basically uses sscanf to match character sets. It's not particularly advanced functionality that cannot be reimplemented although using a standard function for it makes the code clearer.

I am not sure how this would be affected by locale.

**Comment by lmoellendorf** [comment] 2024-03-02 23:40
@sconstanter  @SimonHeffer 
 
Sorry, but I cannot reproduce these issues. I added commit ab196cb3cfc7efdd0bc5a3a7475a373a88b16407 to Test UTF-8 and dots in keys and the [test passed](https://gitlab.com/iniparser/iniparser-meta/-/jobs/6304127136).

For now I will close this issue.

If this is a Windows issue, please help us to get the test build and run on our [Windows runner](https://gitlab.com/iniparser/iniparser-meta/-/blob/main/.gitlab-ci.yml?ref_type=heads#L86) so we can reproduce it. Then this issue may be re-opened.

**Closed by lmoellendorf** 2024-03-02 23:40 UTC
