### ISSUE TITLE
Compile Warning (gcc 8.x)

### ISSUE THREAD

**Issue by mikeqoo1** [ndevilla/iniparser#124] opened 2020-01-03 07:06 UTC
I use gcc version 8.3.1 20190311 (Red Hat 8.3.1-3) (GCC)

```
src/lib/iniparser.c: In function ‘iniparser_load’:
src/lib/iniparser.c:757:32: warning: ‘sprintf’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
             sprintf(tmp, "%s:%s", section, key);
                                ^
src/lib/iniparser.c:757:13: note: ‘sprintf’ output between 2 and 2050 bytes into a destination of size 2049
             sprintf(tmp, "%s:%s", section, key);
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by Crayon2000** [comment] 2020-07-04 14:36
This is a duplicate of issue #95.
Pull request #107 fixed the issue.

**Closed** 2020-07-06 00:07 UTC
